const demo = {
  project: { name: 'Fluance', domain: 'www.fluance.com', lastAudit: 'Sep 21, 2026 · 10:52 AM' },
  metrics: { pages: 312, images: 3112, weight: '150.9 MB', savings: '46.3 MB', issues: 84, score: 64 },
  issues: [
    { tone: 'red', title: 'Oversized image dimensions', sub: 'Assets are served larger than their rendered viewport', count: '42 images' },
    { tone: 'amber', title: 'Legacy format conversion', sub: 'JPEG/PNG opportunities for WebP or AVIF', count: '31 images' },
    { tone: 'blue', title: 'Missing responsive srcset', sub: 'Mobile devices download the full-size source', count: '68 images' },
    { tone: 'amber', title: 'Images missing alt text', sub: 'Accessibility and image-search coverage gap', count: '24 images' },
  ],
  pages: [
    { url: '/products/rt85-reference-turntable', status: 200, title: 'RT85 Reference High Fidelity Turntable', images: 18, issue: '2 issues', severity: 'high' },
    { url: '/products/rt82-automatic-turntable', status: 200, title: 'RT82 Classic High Fidelity Vinyl Turntable', images: 14, issue: '1 issue', severity: 'medium' },
    { url: '/collections/turntables', status: 200, title: 'Turntables | Fluance', images: 39, issue: '6 issues', severity: 'high' },
    { url: '/blogs/audio/how-to-place-speakers', status: 200, title: 'How to Place Your Speakers', images: 9, issue: '0 issues', severity: 'pass' },
  ],
};

let state = { active: 'Overview', auditRunning: false, auditProgress: 0, query: '' };
const app = document.querySelector('#app');
const navItems = [ ['◫', 'Overview'], ['▤', 'Pages'], ['▧', 'Images'], ['⌁', 'Opportunities'], ['◌', 'Compare'], ['⚙', 'Settings'] ];

function shell(content) {
  app.innerHTML = `<div class="app-shell">
    <aside class="sidebar">
      <div class="brand"><div class="brand-mark">◔</div><div><strong>WebOps AI</strong><small>Website intelligence</small></div></div>
      <div><div class="nav-label">Audit workspace</div><nav class="nav">${navItems.map(([icon, label]) => `<button class="${state.active === label ? 'active' : ''}" data-nav="${label}"><span class="nav-icon">${icon}</span><span>${label}</span></button>`).join('')}</nav></div>
      <div class="sidebar-spacer"></div>
      <div class="side-card"><p><span class="status-dot"></span>Evidence engine online</p><strong>Demo data connected</strong><p>Supabase-ready persistence</p></div>
      <div class="nav"><button data-nav="Settings"><span class="nav-icon">⌘</span><span>Workspace settings</span></button></div>
    </aside>
    <main class="main">
      <header class="topbar"><div class="breadcrumb">Projects / <b>${demo.project.name}</b> / ${state.active}</div><div class="top-actions"><span class="badge"><span class="status-dot"></span>Demo mode</span><button class="btn ghost" id="exportBtn">↓ Export CSV</button><button class="btn primary" id="newAuditBtn">＋ New audit</button></div></header>
      <div class="content">${content}</div>
    </main>
  </div>`;
  bindCommon();
}

function overview() {
  return `<div class="page-head"><div><div class="eyebrow">Target website audit</div><h1>${demo.project.domain}</h1><p class="subtitle">Evidence-first crawl, asset intelligence, and performance opportunities.</p></div><div class="head-actions"><button class="btn" id="rerunBtn">↻ Re-run audit</button><button class="btn primary" id="reportBtn">Export report</button></div></div>
  <section class="hero"><div><div class="eyebrow">Latest completed audit · ${demo.project.lastAudit}</div><h2>Opportunity engine found 84 actionable issues</h2><p>The platform keeps measurements separate from interpretation, so every recommendation can be traced back to crawl evidence.</p><div class="hero-meta"><span>Mode <strong>HYBRID</strong></span><span>Coverage <strong>312 / 428 pages</strong></span><span>PageSpeed <strong>${demo.metrics.score}/100</strong></span></div></div><div class="hero-visual"><div class="sparkline">${[35, 46, 42, 58, 54, 70, 66, 82, 74, 92].map(h => `<i style="height:${h}%"></i>`).join('')}</div><div class="hero-visual-label"><span>Audit health trend</span><b>+18%</b></div></div></section>
  <section class="metrics">${metric('Pages crawled', demo.metrics.pages, 'of 428 discovered', 'blue')}${metric('Unique assets', demo.metrics.images, 'deduplicated', 'blue')}${metric('Image weight', demo.metrics.weight, 'transfer payload', 'amber')}${metric('Potential savings', demo.metrics.savings, '-31% estimated', 'green')}${metric('Flagged issues', demo.metrics.issues, 'requiring review', 'red')}${metric('Lighthouse', demo.metrics.score + '/100', 'LCP: 3400ms', 'amber')}</section>
  <div class="grid-2"><section class="panel"><div class="panel-head"><div><h3>Highest-impact findings</h3><span>Prioritized from verified measurements</span></div><button class="btn ghost" data-nav="Opportunities">View all</button></div><div class="panel-body"><div class="issue-list">${demo.issues.map(i => issue(i)).join('')}</div></div></section><section class="panel"><div class="panel-head"><div><h3>Audit trend</h3><span>Last 6 completed runs</span></div><span class="tag pass">Improving</span></div><div class="panel-body"><div class="chart-wrap">${[ ['Sep 1', 52, 42], ['Sep 5', 61, 48], ['Sep 9', 56, 55], ['Sep 13', 73, 61], ['Sep 17', 68, 72], ['Sep 21', 88, 79] ].map(x => `<div class="chart-col"><div class="bar-stack"><i class="bar one" style="height:${x[1]}%"></i><i class="bar two" style="height:${x[2]}%"></i></div><span class="chart-label">${x[0]}</span></div>`).join('')}</div><div class="legend"><span><i class="blue"></i>SEO health</span><span><i class="green"></i>Performance</span></div></div></section></div>
  ${pagesTable()}`;
}

function metric(label, value, note, tone) { return `<div class="metric"><div class="metric-label">${label}</div><div class="metric-value ${tone}">${value}</div><div class="metric-note">${note}</div></div>`; }
function issue(i) { return `<div class="issue"><i class="issue-bar ${i.tone}"></i><div><div class="issue-title">${i.title}</div><div class="issue-sub">${i.sub}</div></div><div class="issue-count">${i.count}</div></div>`; }
function pagesTable() { return `<section class="panel table-panel"><div class="panel-head"><div><h3>Page inventory</h3><span>Latest evidence snapshot</span></div><div class="toolbar"><input class="select" id="pageSearch" placeholder="Search pages…" value="${state.query}" /></div></div><div class="table-scroll"><table><thead><tr><th>URL</th><th>Status</th><th>Title</th><th>Images</th><th>Findings</th></tr></thead><tbody>${demo.pages.filter(p => !state.query || p.url.includes(state.query) || p.title.toLowerCase().includes(state.query.toLowerCase())).map(p => `<tr><td class="mono url">${p.url}</td><td><span class="tag pass">${p.status}</span></td><td>${p.title}</td><td>${p.images}</td><td><span class="tag ${p.severity}">${p.issue}</span></td></tr>`).join('')}</tbody></table></div></section>`; }
function pageView() { return `<div class="page-head"><div><div class="eyebrow">Audit evidence</div><h1>Pages</h1><p class="subtitle">Browse crawl facts before applying rules or AI interpretation.</p></div><button class="btn primary" id="exportBtn">↓ Export pages</button></div>${pagesTable()}`; }
function imagesView() { return `<div class="page-head"><div><div class="eyebrow">Asset intelligence</div><h1>Images</h1><p class="subtitle">Find oversize, format, responsive delivery, and accessibility opportunities.</p></div><button class="btn primary" id="altBtn">✦ Generate alt proposals</button></div><section class="metrics">${metric('Oversized', '42', 'high impact', 'red')}${metric('Legacy format', '31', 'WebP / AVIF', 'amber')}${metric('Missing srcset', '68', 'mobile waste', 'blue')}${metric('Missing alt', '24', 'needs review', 'amber')}${metric('LCP candidates', '17', 'optimization targets', 'green')}${metric('Potential savings', '46.3 MB', 'estimated', 'green')}</section><section class="panel"><div class="panel-head"><div><h3>Image intelligence workflow</h3><span>Evidence → rule → proposal → human review</span></div><span class="tag info">AI suggestions gated</span></div><div class="panel-body"><div class="issue-list">${demo.issues.slice(0, 3).map(issue).join('')}</div></div></section>`; }
function opportunitiesView() { return `<div class="page-head"><div><div class="eyebrow">Actionable intelligence</div><h1>Opportunities</h1><p class="subtitle">Aggregate thousands of findings into business-ready actions.</p></div><button class="btn primary" id="reportBtn">Create executive report</button></div><section class="panel"><div class="panel-head"><div><h3>Top opportunities</h3><span>Ranked from severity, reach, savings, and confidence</span></div><span class="tag high">12 high impact</span></div><div class="table-scroll"><table><thead><tr><th>Opportunity</th><th>Affected</th><th>Est. impact</th><th>Confidence</th><th>Action</th></tr></thead><tbody><tr><td><b>Optimize oversized product images</b><br /><span class="issue-sub">Serve responsive WebP/AVIF renditions</span></td><td>482 pages</td><td class="mono">7.8 GB/mo</td><td><span class="tag pass">94%</span></td><td><button class="btn">Review</button></td></tr><tr><td><b>Reduce redirect chains</b><br /><span class="issue-sub">Convert multi-hop paths to direct redirects</span></td><td>37 URLs</td><td class="mono">High</td><td><span class="tag pass">98%</span></td><td><button class="btn">Review</button></td></tr><tr><td><b>Restore responsive image delivery</b><br /><span class="issue-sub">Add srcset and sizes to mobile-critical images</span></td><td>68 images</td><td class="mono">18.2 MB</td><td><span class="tag medium">87%</span></td><td><button class="btn">Review</button></td></tr></tbody></table></div></section>`; }
function settingsView() { return `<div class="page-head"><div><div class="eyebrow">Workspace configuration</div><h1>Settings</h1><p class="subtitle">Connect persistence later without changing the audit UI.</p></div></div><section class="grid-2"><section class="panel"><div class="panel-head"><h3>Deployment</h3></div><div class="panel-body"><div class="issue-list"><div class="issue"><i class="issue-bar green"></i><div><div class="issue-title">Vercel static app</div><div class="issue-sub">Ready to deploy from GitHub</div></div><span class="tag pass">Ready</span></div><div class="issue"><i class="issue-bar blue"></i><div><div class="issue-title">Serverless audit endpoint</div><div class="issue-sub">/api/audit.js included for MVP crawling</div></div><span class="tag info">Included</span></div><div class="issue"><i class="issue-bar amber"></i><div><div class="issue-title">Supabase persistence</div><div class="issue-sub">Schema and RLS starter included</div></div><span class="tag medium">Optional</span></div></div></div></section><section class="panel"><div class="panel-head"><h3>Architecture guardrails</h3></div><div class="panel-body"><ul class="guardrails"><li>Raw measurements stay separate from AI output.</li><li>Audit results are immutable snapshots.</li><li>AI suggestions require review before changes.</li><li>Supabase is an adapter, not a product dependency.</li></ul></div></section></div>`; }

function render() { const view = state.active === 'Pages' ? pageView() : state.active === 'Images' ? imagesView() : state.active === 'Opportunities' ? opportunitiesView() : state.active === 'Settings' ? settingsView() : overview(); shell(view); }
function bindCommon() {
  document.querySelectorAll('[data-nav]').forEach(b => b.addEventListener('click', () => { state.active = b.dataset.nav; render(); }));
  document.querySelector('#newAuditBtn')?.addEventListener('click', openAudit);
  document.querySelector('#rerunBtn')?.addEventListener('click', openAudit);
  document.querySelector('#exportBtn')?.addEventListener('click', exportCsv);
  document.querySelector('#reportBtn')?.addEventListener('click', () => toast('Report job queued — export will be ready in the Reports view.'));
  document.querySelector('#altBtn')?.addEventListener('click', () => toast('24 evidence-grounded alt-text proposals queued for review.'));
  document.querySelector('#pageSearch')?.addEventListener('input', e => { state.query = e.target.value; render(); const input = document.querySelector('#pageSearch'); input?.focus(); input?.setSelectionRange(state.query.length, state.query.length); });
}
function openAudit() { const backdrop = document.createElement('div'); backdrop.className = 'modal-backdrop'; backdrop.innerHTML = `<div class="modal"><div class="eyebrow">New audit</div><h2>Start an evidence crawl</h2><p>Use HTTP-first discovery with optional rendering. The starter runs in demo mode locally and calls <code>/api/audit</code> when deployed.</p><div class="field"><label for="auditUrl">Website URL</label><input id="auditUrl" value="https://${demo.project.domain}" placeholder="https://example.com" /></div><div class="field"><label for="auditMode">Crawl mode</label><select id="auditMode" class="select"><option>Hybrid — recommended</option><option>Sitemap only</option><option>URL list</option></select></div><div class="modal-actions"><button class="btn" id="cancelAudit">Cancel</button><button class="btn primary" id="startAudit">Start audit</button></div></div>`; document.body.appendChild(backdrop); backdrop.querySelector('#auditUrl').value = 'https://' + demo.project.domain; backdrop.querySelector('#cancelAudit').onclick = () => backdrop.remove(); backdrop.querySelector('#startAudit').onclick = () => runAudit(backdrop, backdrop.querySelector('#auditUrl').value); }
function runAudit(backdrop, url) { state.auditRunning = true; const auditRequest = fetch('/api/audit', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url }) }).then(async response => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'Audit failed.'); return payload; }).catch(error => ({ error: error.message })); const modal = backdrop.querySelector('.modal'); modal.innerHTML = `<div class="eyebrow">Audit in progress</div><h2>Collecting verified evidence</h2><p id="progressText">Discovering sitemap and homepage links…</p><div class="progress"><i id="progressBar" style="width:8%"></i></div><div class="progress-label"><span id="progressStep">Discovery</span><b id="progressPct">8%</b></div>`; let pct = 8; const steps = [['Discovery', 'Discovering sitemap and homepage links…'], ['Fetch', 'Fetching pages with bounded concurrency…'], ['Extract', 'Extracting links, images, and metadata…'], ['Analyze', 'Running deterministic audit rules…'], ['Complete', 'Audit complete — evidence is ready to review.']]; let idx = 0; const timer = setInterval(() => { pct += 23; idx = Math.min(idx + 1, steps.length - 1); modal.querySelector('#progressBar').style.width = `${Math.min(pct, 100)}%`; modal.querySelector('#progressPct').textContent = `${Math.min(pct, 100)}%`; modal.querySelector('#progressStep').textContent = steps[idx][0]; modal.querySelector('#progressText').textContent = steps[idx][1]; if (pct >= 100) { clearInterval(timer); setTimeout(() => { backdrop.remove(); state.auditRunning = false; auditRequest.then(result => toast(result.error ? `Audit demo completed; live endpoint reported: ${result.error}` : `Live page audit complete: ${result.evidence.status} · ${result.evidence.images} images · ${result.findings.length} findings.`)); }, 500); } }, 650); }
function exportCsv() { const header = 'url,status,title,images,findings\n'; const rows = demo.pages.map(p => [p.url, p.status, `"${p.title}"`, p.images, p.issue].join(',')).join('\n'); const blob = new Blob([header + rows], { type: 'text/csv' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'webops-pages.csv'; a.click(); URL.revokeObjectURL(a.href); toast('CSV export downloaded.'); }
function toast(message) { const old = document.querySelector('.toast'); old?.remove(); const el = document.createElement('div'); el.className = 'toast'; el.textContent = message; document.body.appendChild(el); setTimeout(() => el.remove(), 3600); }
render();
