"use client";
/* eslint-disable @next/next/no-img-element -- audit previews show external evidence, not application media. */
import { useCallback, useEffect, useState } from "react";
import { AUDIT_MODES, DEFAULT_CONFIG, modeConfig, type AuditConfig, type AuditMode } from "@/lib/pipeline/config";
import type { AuditJob, EvidenceRecord, Progress } from "@/lib/pipeline/types";
import type { Finding, PageEvidence } from "@/lib/types";
import type { ImageAnalysis } from "@/lib/pipeline/images";
import styles from "./audit-console.module.css";

const VIEWS: Record<string,string>={Overview:"overview",Pages:"pages",Issues:"findings",Links:"links",Images:"images","Image AI":"ai_analyses",Performance:"performance","Core Web Vitals":"performance",Resources:"resources",Accessibility:"findings","Structured Data":"structured_data",Sitemap:"sitemap_urls",Content:"pages","AI Recommendations":"ai_analyses",Opportunities:"opportunities",Reports:"reports","Crawl Comparison":"comparison","Crawl Progress":"tasks",Settings:"settings"};
const aliases:Record<string,string>={Audits:"Overview",Crawler:"Pages",SEO:"Issues",Assets:"Images","Fix Center":"Issues",Analytics:"Overview",Integrations:"Settings"};
type Row=EvidenceRecord<Record<string,unknown>>;
type JsonObject=Record<string,unknown>;
type JobListResponse={jobs:AuditJob[]};
type ConnectionsResponse={credentials:{id:string;display_name:string;provider:string;model_allowlist:string[]}[]};
type JobResponse={job:AuditJob;progress:Progress};
type RecordsResponse={records:Row[];hasMore?:boolean};
const display=(value:unknown)=>value===null || value===undefined?"Not measured":typeof value==="object"?JSON.stringify(value):String(value);
const bytes=(value:unknown)=>typeof value==="number"?`${(value/1024).toFixed(1)} KB`:"Not measured";
async function requestJson<T extends JsonObject = JsonObject>(url:string,init?:RequestInit):Promise<T>{
 let res=await fetch(url,{...init,cache:"no-store"});
 if(res.status===401){const refreshed=await fetch("/api/auth/refresh",{method:"POST"});if(refreshed.ok)res=await fetch(url,{...init,cache:"no-store"});}
 const raw=await res.text();
 let body:JsonObject={};
 if(raw.trim()){
  try{body=JSON.parse(raw) as Record<string,unknown>;}catch{throw new Error(res.ok?"The server returned an invalid response.":`Request failed (HTTP ${res.status}).`);}
 }
 if(!res.ok)throw new Error(typeof body.error === "string" ? body.error : `Request failed (HTTP ${res.status}).`);
 return body as T;
}
const jsonRequest=(method:string,body:unknown):RequestInit=>({method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});

export function AuditConsole({projectId="",initialUrl="",initialJobId="",initialView="Overview",embedded=false}:{projectId?:string;initialUrl?:string;initialJobId?:string;initialView?:string;embedded?:boolean}){
 const [view,setView]=useState(aliases[initialView] || initialView);
 const [jobs,setJobs]=useState<AuditJob[]>([]);const [jobId,setJobId]=useState(initialJobId);const [job,setJob]=useState<AuditJob|null>(null);const [progress,setProgress]=useState<Progress|null>(null);
 const [url,setUrl]=useState(initialUrl);const [config,setConfig]=useState<AuditConfig>(DEFAULT_CONFIG);const [showConfig,setShowConfig]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
 const [rows,setRows]=useState<Row[]>([]);const [offset,setOffset]=useState(0);const [hasMore,setHasMore]=useState(false);const [loading,setLoading]=useState(false);
 const [query,setQuery]=useState("");const [severity,setSeverity]=useState("");const [category,setCategory]=useState("");const [status,setStatus]=useState("");const [source,setSource]=useState("");const [detail,setDetail]=useState<Row|null>(null);const [selected,setSelected]=useState<string[]>([]);const [editedAlt,setEditedAlt]=useState("");
 const [providers,setProviders]=useState<{id:string;display_name:string;provider:string;model_allowlist:string[]}[]>([]);
 const [before,setBefore]=useState("");const [comparison,setComparison]=useState<Record<string,unknown>|null>(null);
 const kind=VIEWS[view] || "pages";
 const loadJobs=useCallback(async()=>{const data=await requestJson<JobListResponse>(`/api/jobs${projectId?`?projectId=${projectId}`:""}`);setJobs(data.jobs || []);setJobId(current=>current || data.jobs?.[0]?.id || "");},[projectId]);
 // Load saved audit state from the server when project scope changes.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{let active=true;void loadJobs().catch(e=>active&&setError(e.message));void requestJson<ConnectionsResponse>(`/api/ai/connections${projectId?`?projectId=${projectId}`:""}`).then(data=>active&&setProviders(data.credentials || [])).catch(()=>{});return()=>{active=false;};},[loadJobs,projectId]);
 useEffect(()=>{
  // Workspace navigation changes the selected evidence view without losing the job.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  setView(aliases[initialView] || initialView);setOffset(0);setSource("");setSelected([]);
 },[initialView]);
 useEffect(()=>{
  if(!jobId)return;let active=true;let timer:ReturnType<typeof setTimeout>;
  const poll=async()=>{try{const data=await requestJson<JobResponse>(`/api/jobs/${jobId}`);if(!active)return;setJob(data.job);setProgress(data.progress);if(["QUEUED","RUNNING","CANCELLING"].includes(data.job.status))timer=setTimeout(poll,2500);}catch(e){if(active)setError(e instanceof Error?e.message:"Unable to load progress.");}};
  void poll();return()=>{active=false;clearTimeout(timer);};
 },[jobId,notice]);
 const loadRows=useCallback(async()=>{
  if(!jobId || ["overview","settings","comparison"].includes(kind))return;
  setLoading(true);try{
   const params=new URLSearchParams({kind,offset:String(offset),limit:"50"});if(query)params.set("q",query);if(severity)params.set("severity",severity);if(status)params.set("status",status);if(source)params.set("source_url",source);
   if(view==="Accessibility")params.set("category","accessibility");else if(category)params.set("category",category);
   const data=await requestJson<RecordsResponse>(`/api/jobs/${jobId}/records?${params}`);setRows(data.records || []);setHasMore(!!data.hasMore);
  }catch(e){setError(e instanceof Error?e.message:"Unable to load evidence.");}finally{setLoading(false);}
 },[jobId,kind,offset,query,severity,status,source,view,category]);
 useEffect(()=>{let active=true;const timer=setTimeout(()=>{if(active)void loadRows();},200);return()=>{active=false;clearTimeout(timer);};},[loadRows,job?.status]);
 const navigate=(next:string,filter="")=>{setView(next);setOffset(0);setSource(filter);setQuery("");setCategory("");setSeverity("");setStatus("");setSelected([]);setDetail(null);};
 const launch=async(mode?:AuditMode)=>{setBusy(true);setError("");try{const chosen=mode?{...modeConfig(mode),credentialId:config.credentialId,model:config.model}:config;const data=await requestJson<{jobId:string}>("/api/jobs",jsonRequest("POST",{url,projectId:projectId || undefined,config:chosen}));setJobId(data.jobId);setJob(null);setProgress(null);setView("Overview");setNotice("Audit queued. It continues on the server when this page closes.");await loadJobs();}catch(e){setError(e instanceof Error?e.message:"Unable to queue audit.");}finally{setBusy(false);}};
 const control=async(action:string)=>{setBusy(true);try{await requestJson(`/api/jobs/${jobId}`,jsonRequest("PATCH",{action}));setNotice(`${action} requested at ${new Date().toLocaleTimeString()}`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const review=async(keys:string[],next:string,alt?:string)=>{try{await requestJson(`/api/jobs/${jobId}/records`,jsonRequest("PATCH",{kind,keys,status:next,editedAlt:alt}));setDetail(null);setSelected([]);await loadRows();}catch(e){setError((e as Error).message);}};
 const generate=async(keys:string[])=>{setBusy(true);try{await requestJson(`/api/jobs/${jobId}/ai`,jsonRequest("POST",{kind:kind==="images"?"ai_image":"ai_page",keys,credentialId:config.credentialId,model:config.model}));setNotice("AI analysis queued. Open AI Recommendations to review its progress and results.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const compare=async()=>{setBusy(true);try{const data=await requestJson<JsonObject>(`/api/jobs/${jobId}/compare?before=${before}`);setComparison(data);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const patch=<K extends keyof AuditConfig>(key:K,value:AuditConfig[K])=>setConfig(c=>({...c,[key]:value}));
 const selectedAll=rows.length>0 && selected.length===rows.length;
 const health=job?.summary.health as {overall:number;grade:string;categories:Record<string,number>}|null;

 return <section className={styles.console}>
  <header className={styles.header}><div><small>WEBOPS AI · EVIDENCE WORKSPACE</small><h1>{embedded?view:"Website intelligence"}</h1></div>{!embedded&&<a href="/workspace" className="btn ghost sm">Workspace</a>}</header>
  <form className={styles.launch} onSubmit={e=>{e.preventDefault();void launch();}}>
   <label>Website URL<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com" required/></label>
   <label>Audit mode<select value={config.mode} onChange={e=>setConfig({...modeConfig(e.target.value as AuditMode),credentialId:config.credentialId,model:config.model})}>{AUDIT_MODES.map(mode=><option key={mode}>{mode}</option>)}</select></label>
   <button className="btn" disabled={busy}>Start audit</button><button type="button" className="btn ghost" onClick={()=>setShowConfig(v=>!v)}>Configure</button><button type="button" className="btn" disabled={busy || !url} onClick={()=>void launch("God Mode")}>Run God Mode</button>
  </form>
  {(showConfig || view==="Settings")&&<section className={styles.panel}><h2>Audit configuration</h2><p>Settings apply to the next audit. All modes are editable presets. Robots policy and access restrictions are reported and respected.</p><div className={styles.config}>
   {([['maxPages','Maximum pages'],['maxDepth','Maximum depth'],['concurrency','Concurrent requests'],['timeoutMs','Request timeout (ms)'],['retries','Retries'],['delayMs','Delay between batches (ms)'],['maxImages','Maximum images'],['maxResources','Maximum resources / links'],['maxSitemaps','Maximum sitemaps'],['maxAiTasks','AI tasks per audit'],['maxPerformancePages','PageSpeed pages'],['scrollSteps','Lazy-load scroll steps'],['largeImageBytes','Large-image threshold (bytes)'],['oversizedRatio','Oversized-image ratio'],['minWords','Thin-page word threshold'],['maxBytes','Page byte limit'],['maxImageBytes','Image byte limit']] as [keyof AuditConfig,string][]).map(([key,label])=><label key={key}>{label}<input type="number" min="0" step={key==="oversizedRatio"?"0.1":"1"} value={Number(config[key])} onChange={e=>patch(key,Number(e.target.value))}/></label>)}
   <label>Rendering<select value={config.rendering} onChange={e=>patch("rendering",e.target.value as AuditConfig["rendering"])}><option value="http">HTTP only</option><option value="adaptive">Render low-content JavaScript pages</option><option value="browser">Browser rendering</option></select></label>
   <label>Query parameters<select value={config.queryPolicy} onChange={e=>patch("queryPolicy",e.target.value as AuditConfig["queryPolicy"])}><option value="preserve">Preserve exactly</option><option value="strip-tracking">Remove known tracking parameters</option><option value="drop">Remove all query parameters</option></select></label>
   <label>User agent<input value={config.userAgent} onChange={e=>patch("userAgent",e.target.value)}/></label>
   <label>Viewport width<input type="number" value={config.viewport.width} onChange={e=>patch("viewport",{...config.viewport,width:Number(e.target.value)})}/></label><label>Viewport height<input type="number" value={config.viewport.height} onChange={e=>patch("viewport",{...config.viewport,height:Number(e.target.value)})}/></label><label>Device pixel ratio<input type="number" min="1" max="3" step="0.5" value={config.viewport.deviceScaleFactor} onChange={e=>patch("viewport",{...config.viewport,deviceScaleFactor:Number(e.target.value)})}/></label>
   <label>Include URL patterns (one per line)<textarea value={config.includePatterns.join("\n")} onChange={e=>patch("includePatterns",e.target.value.split("\n").filter(Boolean))} placeholder="https://example.com/products/*"/></label><label>Exclude URL patterns<textarea value={config.excludePatterns.join("\n")} onChange={e=>patch("excludePatterns",e.target.value.split("\n").filter(Boolean))}/></label>
   {(["images","resources","performance","accessibility","ai","checkExternalLinks"] as const).map(key=><label className={styles.check} key={key}><input type="checkbox" checked={config[key]} onChange={e=>patch(key,e.target.checked)}/>{key}</label>)}<label className={styles.check}><input type="checkbox" checked={config.viewport.mobile} onChange={e=>patch("viewport",{...config.viewport,mobile:e.target.checked})}/>Mobile device</label>
   <label>AI provider<select value={config.credentialId} onChange={e=>patch("credentialId",e.target.value)}><option value="">Server default</option>{providers.map(p=><option key={p.id} value={p.id}>{p.display_name} · {p.provider}</option>)}</select></label><label>AI model<input value={config.model} onChange={e=>patch("model",e.target.value)} placeholder="Provider default (vision-capable for images)"/></label>
  </div><details><summary>Score weights</summary><div className={styles.config}>{Object.entries(config.scoreWeights).map(([key,value])=><label key={key}>{key}<input type="number" min="0" max="100" value={value} onChange={e=>patch("scoreWeights",{...config.scoreWeights,[key]:Number(e.target.value)})}/></label>)}</div></details><a href="/ai-studio">Manage encrypted AI providers</a></section>}
  {error&&<p className={styles.error} role="alert">{error} <button onClick={()=>setError("")}>Dismiss</button></p>}{notice&&<p role="status" className={styles.notice}>{notice}</p>}
  <div className={styles.toolbar}><label>Saved audit<select value={jobId} onChange={e=>{setJobId(e.target.value);setOffset(0);setSelected([]);setDetail(null);}}><option value="">Select an audit</option>{jobs.map(j=><option key={j.id} value={j.id}>{new Date(j.created_at).toLocaleString()} · {j.config.mode} · {j.status} · {j.url}</option>)}</select></label><button className="btn ghost sm" onClick={()=>void loadJobs().catch(e=>setError(e.message))}>Refresh history</button><a href="/audit" className="btn ghost sm">Legacy audit history</a></div>
  {job&&<>
   <section className={styles.progress} aria-live="polite"><strong>{job.status}</strong><span>{job.stage}</span><span>{progress?.pages || 0} pages · {progress?.images || 0} images · {progress?.done || 0}/{progress?.total || 0} tasks</span><span>{progress?.failed || 0} failed requests</span>{["QUEUED","RUNNING"].includes(job.status)&&<button onClick={()=>void control("pause")} disabled={busy}>Pause</button>}{["PAUSED","FAILED"].includes(job.status)&&<button onClick={()=>void control("resume")} disabled={busy}>Resume / retry</button>}{!["COMPLETED","CANCELLED"].includes(job.status)&&<button onClick={()=>void control("cancel")} disabled={busy}>Cancel</button>}{job.error&&<p>{job.error} {job.status==="QUEUED"&&<button onClick={()=>void control("resume")}>Retry dispatch</button>}</p>}</section>
   <nav className={styles.tabs} aria-label="Evidence sections">{Object.keys(VIEWS).map(v=><button key={v} className={view===v?styles.active:""} onClick={()=>navigate(v)}>{v}</button>)}</nav>
   {view==="Overview"&&<><div className={styles.metrics}><button onClick={()=>navigate("Issues")}><small>Evidence health</small><strong>{health?`${health.overall} · ${health.grade}`:"Not scored yet"}</strong></button><button onClick={()=>navigate("Pages")}><small>Pages processed</small><strong>{progress?.pages || 0}</strong></button><button onClick={()=>navigate("Images")}><small>Images processed</small><strong>{progress?.images || 0}</strong></button><button onClick={()=>navigate("Crawl Progress")}><small>Failed requests</small><strong>{progress?.failed || 0}</strong></button></div><section className={styles.panel}><h2>Coverage and priorities</h2><p>Evidence is saved as work finishes. Open Pages, Images, or Issues to inspect it. A completed job may have partial coverage; review failed requests, restrictions, and configured limits.</p>{health&&<div className={styles.metrics}>{Object.entries(health.categories).map(([key,value])=><button key={key} onClick={()=>{navigate("Issues");setCategory(key);}}><small>{key}</small><strong>{value}</strong></button>)}</div>}<dl><dt>Requested URL</dt><dd>{job.url}</dd><dt>Started</dt><dd>{new Date(job.created_at).toLocaleString()}</dd><dt>Last progress</dt><dd>{new Date(job.updated_at).toLocaleString()}</dd><dt>Limits reached</dt><dd>{display(job.summary.limited || "None reported")}</dd></dl><button className="btn ghost sm" onClick={()=>navigate("Opportunities")}>Prioritized action plan</button><button className="btn ghost sm" onClick={()=>{navigate("Crawl Progress");}}>Inspect requests and restrictions</button></section></>}
   {view==="Crawl Comparison"&&<section className={styles.panel}><h2>Compare saved evidence</h2><select value={before} onChange={e=>setBefore(e.target.value)}><option value="">Choose earlier audit</option>{jobs.filter(j=>j.id!==job.id).map(j=><option key={j.id} value={j.id}>{j.url} · {new Date(j.created_at).toLocaleString()}</option>)}</select><button className="btn" onClick={()=>void compare()} disabled={!before || busy}>Compare</button>{comparison&&<pre>{JSON.stringify(comparison,null,2)}</pre>}</section>}
   {view==="Reports"&&<section className={styles.panel}><h2>Export measured evidence</h2><p>Exports include collected evidence and its limitations. JSON streams records; Excel separates pages, issues, images, links, performance, and AI recommendations.</p><div className={styles.toolbar}>{["json","csv","xlsx"].map(format=><a className="btn" key={format} href={`/api/jobs/${job.id}/export?format=${format}`}>Download {format.toUpperCase()}</a>)}</div></section>}
   {!["overview","settings","comparison"].includes(kind)&&<section className={styles.panel}><div className={styles.toolbar}><h2>{view}</h2><input aria-label="Search evidence URLs" value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}} placeholder="Filter URL…"/>{kind==="findings"&&<><select aria-label="Severity" value={severity} onChange={e=>{setSeverity(e.target.value);setOffset(0);}}><option value="">All severities</option>{["critical","high","medium","low","info"].map(v=><option key={v}>{v}</option>)}</select><select aria-label="Category" value={category} onChange={e=>{setCategory(e.target.value);setOffset(0);}}><option value="">All categories</option>{Object.keys(DEFAULT_CONFIG.scoreWeights).map(v=><option key={v}>{v}</option>)}</select></>}{["findings","ai_analyses"].includes(kind)&&<select aria-label="Review status" value={status} onChange={e=>{setStatus(e.target.value);setOffset(0);}}><option value="">All statuses</option>{["open","ignored","resolved","accepted","rejected"].map(v=><option key={v}>{v}</option>)}</select>}<button onClick={()=>void loadRows()}>Refresh</button></div>
    {source&&<p>Source page: {source} <button onClick={()=>setSource("")}>Clear</button></p>}
    {selected.length>0&&<div className={styles.toolbar}><span>{selected.length} selected</span>{["images","pages"].includes(kind)&&<button className="btn sm" disabled={busy} onClick={()=>void generate(selected)}>Generate AI recommendations</button>}{["findings","ai_analyses"].includes(kind)&&<>{["accepted","ignored","open",...(kind==="ai_analyses"?["rejected"]:[])].map(next=><button key={next} onClick={()=>void review(selected,next)}>{next}</button>)}</>}</div>}
    {loading?<p>Loading evidence…</p>:rows.length===0?<p>No matching evidence has been collected. Check enabled analyzers, crawl progress, filters, and failed requests.</p>:<div className={styles.tableWrap}><table><thead><tr><th><input type="checkbox" aria-label="Select visible records" checked={selectedAll} onChange={()=>setSelected(selectedAll?[]:rows.map(r=>r.key))}/></th><th>Evidence</th><th>Observation</th><th>Status / details</th><th>Actions</th></tr></thead><tbody>{rows.map((row,index)=>{
      const page=row.data as unknown as PageEvidence;const image=row.data as unknown as ImageAnalysis;const finding=row.data as unknown as Finding;
      return <tr key={row.key || index}><td><input type="checkbox" aria-label={`Select ${row.title || row.url}`} checked={selected.includes(row.key)} onChange={()=>setSelected(s=>s.includes(row.key)?s.filter(k=>k!==row.key):[...s,row.key])}/></td><td>{kind==="images"&&<img src={row.url} alt="Audited image preview" referrerPolicy="no-referrer" loading="lazy" className={styles.thumbnail}/>}<button className={styles.textButton} onClick={()=>{setDetail(row);setEditedAlt(String(row.data?.editedAlt || (row.data?.recommendation as Record<string,unknown>)?.alt || ""));}}>{row.title || (kind==="pages"?page.title:null) || row.url}</button><small className={styles.url}>{row.url}</small>{row.source_url&&<button className={styles.textButton} onClick={()=>{navigate("Pages");setQuery(row.source_url!);}}>Source page</button>}</td>
      <td>{kind==="pages"?<>{page.status} · {page.wordCount} words<br/>{page.rendered?"Browser rendered":"HTTP evidence"}<br/>{page.indexable?"Indexable":"Not indexable"}</>:kind==="images"?<>{bytes(image.bytes)} · {image.format || image.mime}<br/>{image.width ?? "?"} × {image.height ?? "?"}<br/>Estimated savings: {bytes(image.estimatedSavingsBytes)}</>:kind==="findings"?<>{finding.severity} · {finding.category}<br/>{finding.evidence?.slice(0,160)}</>:kind==="tasks"?<>{display((row as unknown as Record<string,unknown>).kind)} · {display((row as unknown as Record<string,unknown>).attempts)} attempts</>:<>{display(row.data?.status ?? row.data?.types ?? row.data?.strategy ?? row.data?.anchor ?? row.data?.type ?? "Open evidence")}</>}</td>
      <td>{row.status || "collected"}{kind==="images"&&<small>{image.error || image.confidence}</small>}{kind==="tasks"&&<small>{display((row as unknown as Record<string,unknown>).error)}</small>}</td><td><button onClick={()=>setDetail(row)}>Inspect</button>{kind==="pages"&&<button onClick={()=>navigate("Links",row.url)}>Links from page</button>}{["images","pages"].includes(kind)&&<button disabled={busy} onClick={()=>void generate([row.key])}>{kind==="images"?"Generate alt":"Analyze content"}</button>}{kind==="findings"&&<button onClick={()=>void review([row.key],"accepted")}>Accept action</button>}</td></tr>;
    })}</tbody></table></div>}
    <div className={styles.toolbar}><button disabled={offset===0} onClick={()=>{setOffset(Math.max(0,offset-50));setSelected([]);}}>Previous</button><span>Page {Math.floor(offset/50)+1}</span><button disabled={!hasMore} onClick={()=>{setOffset(offset+50);setSelected([]);}}>Next</button></div>
   </section>}
  </>}
  {!jobId&&<section className={styles.panel}><h2>Start with a website</h2><p>Choose an audit mode, adjust its coverage, and start. Pages, images, links, findings, and recommendations will appear as evidence is collected.</p></section>}
  {detail&&<div className={styles.backdrop} onClick={e=>e.target===e.currentTarget&&setDetail(null)}><section role="dialog" aria-modal="true" aria-label="Evidence details" className={styles.detail}><button className={styles.close} onClick={()=>setDetail(null)}>Close</button><h2>{detail.title || detail.url}</h2><a href={detail.url} target="_blank" rel="noreferrer">Open source URL</a>{detail.kind==="images"&&<img className={styles.preview} src={detail.url} alt="Audited image" referrerPolicy="no-referrer"/>}{detail.kind==="ai_analyses"&&<><label>Edit recommended alt<textarea value={editedAlt} onChange={e=>setEditedAlt(e.target.value)}/></label><div className={styles.toolbar}><button onClick={()=>void review([detail.key],"accepted",editedAlt)}>Accept recommendation</button><button onClick={()=>void review([detail.key],"rejected")}>Reject</button></div></>}<pre>{JSON.stringify(detail.data || detail,null,2)}</pre>{detail.kind==="findings"&&<div className={styles.toolbar}>{["open","ignored","accepted","resolved"].map(next=><button key={next} onClick={()=>void review([detail.key],next)}>{next}</button>)}<p>Manual status is your review decision. Use a comparison with a follow-up audit to verify a fix.</p></div>}</section></div>}
 </section>;
}
