"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

export default function AcceptInvitationPage() {
  const router = useRouter(); const [token, setToken] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { setToken(new URLSearchParams(window.location.search).get("token") || ""); }, []);
  async function accept() { if (!token) return; setBusy(true); setError(""); setMessage(""); const response = await fetch("/api/organizations/invitations/accept", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token }) }); const data = await response.json(); if (response.ok) { setMessage("Invitation accepted. Opening your workspace…"); setTimeout(() => router.replace("/workspace"), 600); } else setError(data.error || "Unable to accept invitation."); setBusy(false); }
  return <main style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: 24, background: "#070b15", color: "#eef2ff" }}><section style={{ width: "min(520px,100%)", padding: 32, border: "1px solid #26304a", borderRadius: 20, background: "#101728" }}><small style={{ letterSpacing: ".14em", color: "#7d96ee" }}>WEBOPS AI / WORKSPACE ACCESS</small><h1>Accept workspace invitation</h1><p style={{ color: "#91a0bd", lineHeight: 1.6 }}>Sign in with the invited email address, then accept this invitation to join the governed workspace.</p><label style={{ display: "grid", gap: 8 }}>Invitation token<input value={token} onChange={(event) => setToken(event.target.value)} placeholder="Paste invitation token" style={{ padding: 12, borderRadius: 10, border: "1px solid #34415f", background: "#090f1e", color: "white" }} /></label>{error && <p style={{ color: "#ffb4bd" }}>{error}</p>}{message && <p style={{ color: "#a9f3d1" }}>{message}</p>}<button onClick={accept} disabled={busy || !token} style={{ marginTop: 18, padding: "12px 16px", border: 0, borderRadius: 10, background: "linear-gradient(135deg,#5c7cff,#7e5cff)", color: "white", fontWeight: 800 }}>{busy ? "Accepting…" : "Accept invitation"}</button></section></main>;
}
