"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import styles from "./studio.module.css";

type Organization={id:string;name:string}; type Membership={organizations:Organization|null}; type VaultItem={id:string;provider:string;display_name:string;key_hint:string|null;base_url:string|null;model_allowlist:string[];status:string;rotated_at:string|null};
export default function AiStudioPage(){
 const [organization,setOrganization]=useState<Organization|null>(null); const [items,setItems]=useState<VaultItem[]>([]); const [provider,setProvider]=useState("openrouter"); const [displayName,setDisplayName]=useState(""); const [apiKey,setApiKey]=useState(""); const [baseUrl,setBaseUrl]=useState(""); const [models,setModels]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 async function load(org?:Organization|null){const target=org||organization;if(!target)return;const response=await fetch(`/api/provider-credentials?organizationId=${encodeURIComponent(target.id)}`,{cache:"no-store"});const data=await response.json();if(response.ok)setItems(data.credentials||[]);else setError(data.error||"Unable to load credentials.");}
 useEffect(()=>{fetch("/api/organizations",{cache:"no-store"}).then(async response=>{const data=await response.json() as {memberships?:Membership[]};const org=(data.memberships||[]).map(item=>item.organizations).find((item):item is Organization=>Boolean(item))||null;setOrganization(org);if(org)await load(org);}).catch(()=>setError("Unable to load AI Studio."));},[]);
 async function save(){if(!organization)return;setBusy(true);setError("");setMessage("");const response=await fetch("/api/provider-credentials",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationId:organization.id,provider,displayName:displayName||provider,apiKey,baseUrl:baseUrl||undefined,modelAllowlist:models.split(",").map(v=>v.trim()).filter(Boolean),scopes:["chat","generate","models"]})});const data=await response.json();if(response.ok){setApiKey("");setMessage("Credential encrypted and stored. The secret will not be displayed again.");await load();}else setError(data.error||"Unable to save credential.");setBusy(false);}
 async function test(id:string){setBusy(true);setError("");setMessage("");const response=await fetch("/api/ai/test",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({credentialId:id})});const data=await response.json();if(response.ok)setMessage(data.message||"Provider connection succeeded.");else setError(data.error||"Connection test failed.");setBusy(false);}
 async function revoke(id:string){if(!organization)return;setBusy(true);const response=await fetch("/api/provider-credentials",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationId:organization.id,credentialId:id})});const data=await response.json();if(response.ok){setMessage("Credential revoked.");await load();}else setError(data.error||"Unable to revoke credential.");setBusy(false);}
 return <main className={styles.page}><header><div><span>WEBOPS AI / GOVERNED INTELLIGENCE</span><h1>AI Studio</h1><p>Encrypted provider credentials, model controls, routing and evaluation foundations.</p></div><Link href="/workspace">← Command Center</Link></header>{error&&<div className={styles.error}>{error}</div>}{message&&<div className={styles.success}>{message}</div>}<section className={styles.grid}><article className={styles.card}><span>ADD PROVIDER</span><h2>Secure credential vault</h2><p>The key is encrypted server-side with AES-256-GCM and never returned after creation.</p><label>Provider<select value={provider} onChange={e=>setProvider(e.target.value)}><option value="openrouter">OpenRouter</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="google">Google Gemini</option><option value="groq">Groq</option><option value="custom">Custom endpoint</option></select></label><label>Display name<input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Production AI"/></label><label>API key<input type="password" autoComplete="new-password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="Stored once, never displayed"/></label>{provider==="custom"&&<label>HTTPS base URL<input value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="https://api.example.com/v1"/></label>}<label>Model allowlist<input value={models} onChange={e=>setModels(e.target.value)} placeholder="model-a, model-b"/></label><button onClick={save} disabled={busy||!organization||!apiKey}>{busy?"Securing…":"Encrypt and save"}</button></article><article className={styles.card}><span>ACTIVE CONNECTIONS</span><h2>Provider governance</h2><p>Test or revoke credentials without exposing secret values.</p><div className={styles.list}>{items.length?items.map(item=><div key={item.id}><div><b>{item.display_name}</b><small>{item.provider} · •••• {item.key_hint||"hidden"}</small><small>{item.model_allowlist?.length?item.model_allowlist.join(", "):"All models allowed"}</small></div><em className={item.status==="active"?styles.active:styles.revoked}>{item.status}</em><button onClick={()=>test(item.id)} disabled={busy||item.status!=="active"}>Test</button><button onClick={()=>revoke(item.id)} disabled={busy||item.status!=="active"}>Revoke</button></div>):<div className={styles.empty}>No stored credentials. Add the first governed provider.</div>}</div></article></section></main>;
}
